"""
CI/CD Pipeline Generator using Google Gemini AI.
Generates hardened GitHub Actions YAML tailored to the detected tech stack.
"""
import re
from typing import Any
from app.utils.config import settings
from app.utils.logger import get_logger

log = get_logger(__name__)

try:
    import google.generativeai as genai
    _model = genai.GenerativeModel(settings.GEMINI_MODEL)
    GEMINI_AVAILABLE = bool(settings.GEMINI_API_KEY)
except Exception:
    _model = None
    GEMINI_AVAILABLE = False


_CICD_PROMPT = """\
You are a DevSecOps engineer. Generate a production-ready GitHub Actions CI/CD pipeline for
a {language} project{framework_info}.

Tech stack context:
- Language: {language}
- Frameworks: {frameworks}
- Has Docker: {has_docker}
- Package manifests: {manifests}
- Repository: {repo_name}
- Branch strategy: main + develop

Security requirements (MUST include):
1. Semgrep SAST scan (using semgrep/semgrep-action)
2. Dependency vulnerability audit (language-appropriate tool)
3. Secret scanning (using trufflesecurity/trufflehog or similar)
4. Trivy container/filesystem scan if Docker is present
5. Fail the pipeline if CRITICAL vulnerabilities are found

Pipeline stages (in order):
1. security-scan (SAST + secrets + dependency audit)
2. build-and-test (install, build, unit tests, coverage)
3. docker-build (if Has Docker = true, push to GHCR)
4. deploy (conditional on main branch only)

Return ONLY the raw YAML content. Do NOT include markdown fences. No explanations.
"""

# Template pipelines per language (used as fallback)
_PIPELINE_TEMPLATES: dict[str, str] = {
    "python": """\
name: ARK Secure CI/CD — Python
# Generated by ARK DevSecOps AI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.11'

jobs:
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
          auditOn: push
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  build-and-test:
    name: 🔨 Build & Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dependency Audit
        run: pip-audit --vulnerability-service osv

      - name: Lint (Ruff)
        run: |
          pip install ruff
          ruff check .

      - name: Type Check (mypy)
        run: |
          pip install mypy
          mypy . --ignore-missing-imports || true

      - name: Run Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml

  deploy:
    name: 🚀 Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Production
        run: echo "Add your deployment commands here"
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
""",
    "javascript": """\
name: ARK Secure CI/CD — Node.js
# Generated by ARK DevSecOps AI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  build-and-test:
    name: 🔨 Build & Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: NPM Audit
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint --if-present

      - name: Type Check
        run: npm run typecheck --if-present || true

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm test -- --coverage --watchAll=false

  deploy:
    name: 🚀 Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Add your deployment commands here"
""",
    "java": """\
name: ARK Secure CI/CD — Java
# Generated by ARK DevSecOps AI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  build-and-test:
    name: 🔨 Build & Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Build and Test (Maven)
        run: mvn -B verify --file pom.xml

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: ${{ github.repository }}
          path: .
          format: HTML
          failBuildOnCVSS: 7

  deploy:
    name: 🚀 Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo "Add your deployment commands here"
""",
}

_DEFAULT_TEMPLATE = _PIPELINE_TEMPLATES["python"]


async def generate_cicd_pipeline(
    repo_name: str,
    structure: dict[str, Any],
) -> str:
    """
    Generate a GitHub Actions CI/CD YAML pipeline.

    First tries Gemini for a tailored pipeline;
    falls back to a language-specific template if Gemini is unavailable.

    Args:
        repo_name: Repository full name (owner/repo).
        structure: Output from RepoClonerService.analyse_structure().

    Returns:
        YAML string ready to write to .github/workflows/ark-pipeline.yml.
    """
    language = structure.get("language", "python")
    frameworks = structure.get("frameworks", [])
    has_docker = structure.get("has_docker", False)
    manifests = structure.get("package_manifests", [])

    if GEMINI_AVAILABLE and _model:
        framework_info = (
            f" using {', '.join(frameworks)}" if frameworks else ""
        )
        prompt = _CICD_PROMPT.format(
            language=language,
            framework_info=framework_info,
            frameworks=", ".join(frameworks) or "none",
            has_docker=has_docker,
            manifests=", ".join(manifests) or "none",
            repo_name=repo_name,
        )
        log.info("Generating CI/CD pipeline via Gemini…")
        try:
            response = _model.generate_content(prompt)
            raw = response.text.strip()
            # Strip markdown fences if present
            raw = re.sub(r"^```(?:yaml|yml)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
            if raw.startswith("name:") or "jobs:" in raw:
                log.info("CI/CD YAML generated by Gemini successfully")
                return raw
        except Exception as exc:
            log.error(f"Gemini CI/CD generation error: {exc}")

    # Fallback to template
    log.info(f"Using template CI/CD pipeline for language: {language}")
    yaml = _PIPELINE_TEMPLATES.get(language, _DEFAULT_TEMPLATE)

    # Inject repo name
    yaml = yaml.replace("ARK Secure CI/CD —", f"ARK Secure CI/CD — {repo_name} —", 1)
    return yaml
