import { useState } from "react";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { Copy, Download, GitBranch, Wand2, RefreshCw, CheckCircle } from "lucide-react";
import { toast } from "sonner";

const repos = ["frontend-app", "api-gateway", "auth-service", "payment-service"];

const generateYaml = (repo: string) => `name: ARK Secure CI/CD Pipeline
# Generated by ARK DevSecOps AI for: ${repo}
# Generated: ${new Date().toISOString().split("T")[0]}

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  security-scan:
    name: 🔒 ARK Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ARK Security Scanner
        uses: ark-devsecops/scanner@v2
        with:
          severity-threshold: medium
          fail-on-vulnerability: true
          output-format: sarif

      - name: Dependency Vulnerability Audit
        run: npm audit --audit-level=high

      - name: SAST Static Analysis
        uses: ark-devsecops/sast@v1
        with:
          language: typescript
          ruleset: owasp-top-10

      - name: Secret Detection
        uses: ark-devsecops/secret-scan@v1

      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ark-results.sarif

  build-and-test:
    name: 🔨 Build & Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: \${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test -- --coverage

      - name: Build application
        run: npm run build

  deploy:
    name: 🚀 Deploy
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "Deploying ${repo} securely to production..."
          # Add your deployment commands here`;

const CICDGeneratorPage = () => {
  const [selectedRepo, setSelectedRepo] = useState(repos[0]);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const yamlCode = generateYaml(selectedRepo);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => setGenerating(false), 1500);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(yamlCode);
    setCopied(true);
    toast.success("Pipeline YAML copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([yamlCode], { type: "text/yaml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ark-pipeline.yml";
    a.click();
    toast.success("Pipeline file downloaded!");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold mb-1">CI/CD Pipeline Generator</h1>
        <p className="text-sm text-muted-foreground">AI-generated secure GitHub Actions pipeline for your repository.</p>
      </div>

      {/* Config panel */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass rounded-xl p-5"
      >
        <div className="flex flex-wrap items-center gap-4">
          <div>
            <label className="text-xs text-muted-foreground mb-1.5 block">Select Repository</label>
            <select
              value={selectedRepo}
              onChange={(e) => setSelectedRepo(e.target.value)}
              className="bg-muted rounded-lg px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-primary/60 font-mono"
            >
              {repos.map((r) => (
                <option key={r} value={r}>{r}</option>
              ))}
            </select>
          </div>
          <div className="flex-1" />
          <Button
            onClick={handleGenerate}
            className="bg-primary text-primary-foreground hover:bg-primary/90 gap-2"
            disabled={generating}
          >
            {generating ? (
              <RefreshCw className="w-4 h-4 animate-spin" />
            ) : (
              <Wand2 className="w-4 h-4" />
            )}
            {generating ? "Generating..." : "Regenerate Pipeline"}
          </Button>
        </div>
      </motion.div>

      {/* Code editor */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="glass rounded-xl overflow-hidden"
      >
        {/* Editor header */}
        <div className="flex items-center justify-between p-4 border-b border-border/50 bg-muted/30">
          <div className="flex items-center gap-3">
            <div className="flex gap-1.5">
              <div className="w-3 h-3 rounded-full bg-critical/80" />
              <div className="w-3 h-3 rounded-full bg-warning/80" />
              <div className="w-3 h-3 rounded-full bg-neon-green/80" />
            </div>
            <span className="text-xs text-muted-foreground font-mono">.github/workflows/ark-pipeline.yml</span>
          </div>
          <div className="flex gap-2">
            <Button variant="ghost" size="sm" onClick={handleCopy} className="gap-1.5 text-xs h-8">
              {copied ? (
                <CheckCircle className="w-3.5 h-3.5 text-neon-green" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button variant="ghost" size="sm" onClick={handleDownload} className="gap-1.5 text-xs h-8">
              <Download className="w-3.5 h-3.5" /> Download
            </Button>
            <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90 gap-1.5 text-xs h-8">
              <GitBranch className="w-3.5 h-3.5" /> Apply to Repo
            </Button>
          </div>
        </div>

        {/* YAML code with basic syntax highlighting */}
        <div className="overflow-x-auto p-6 bg-background/40">
          <pre className="font-mono text-xs leading-relaxed text-foreground/90">
            {yamlCode.split("\n").map((line, i) => {
              const trimmed = line.trimStart();
              const indent = line.length - trimmed.length;
              let cls = "text-foreground/90";
              if (trimmed.startsWith("#")) cls = "text-muted-foreground/70 italic";
              else if (trimmed.startsWith("name:") || trimmed.startsWith("on:") || trimmed.startsWith("jobs:") || trimmed.startsWith("env:")) cls = "text-neon-purple";
              else if (trimmed.match(/^[a-z-]+:$/) || trimmed.match(/^[a-z-]+\s*:/)) cls = "text-neon-cyan";
              else if (trimmed.startsWith("- ") || trimmed.startsWith("uses:") || trimmed.startsWith("run:")) cls = "text-neon-green";

              return (
                <span key={i} className="block">
                  <span className="text-muted-foreground/30 select-none mr-4 text-right inline-block w-7 text-[10px]">{i + 1}</span>
                  <span className={cls}>{line}</span>
                </span>
              );
            })}
          </pre>
        </div>
      </motion.div>

      {/* Pipeline jobs visualization */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="glass rounded-xl p-5"
      >
        <h3 className="text-sm font-semibold mb-4">Pipeline Structure</h3>
        <div className="flex items-center gap-0 flex-wrap">
          {[
            { name: "Security Scan", icon: "🔒", color: "border-neon-cyan/40 bg-neon-cyan/5" },
            { name: "Build & Test", icon: "🔨", color: "border-neon-blue/40 bg-neon-blue/5" },
            { name: "Deploy", icon: "🚀", color: "border-neon-green/40 bg-neon-green/5" },
          ].map((job, i, arr) => (
            <div key={job.name} className="flex items-center">
              <div className={`rounded-xl border px-5 py-3 ${job.color}`}>
                <div className="text-lg mb-1">{job.icon}</div>
                <p className="text-xs font-medium">{job.name}</p>
              </div>
              {i < arr.length - 1 && (
                <div className="w-8 flex items-center justify-center">
                  <div className="w-full h-0.5 bg-gradient-to-r from-neon-cyan/40 to-neon-blue/40" />
                </div>
              )}
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default CICDGeneratorPage;
